from automation.flex_gui.RightInfo import screen, query, datafeed, utils
from win32com.client import Dispatch


class Worker:

    def __init__(
        self,
        queryFromVSD: query.DanhSachQuyenVSD,
        queryFromF220001: query.F220001,
        queryFromRSE0008: query.ChungKhoanRSE0008,
        queryFromLog: query.LogTable,
        mainScreen: screen.MainScreen,
        mailRecipients: str,
    ):

        self.dataFeed = datafeed.DataFeed(
            queryFromVSD,
            queryFromF220001,
            queryFromRSE0008,
            queryFromLog,
        )
        self.mainScreen = mainScreen
        self.__outlook = Dispatch('outlook.application')
        self.mailRecipients = mailRecipients


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob1(self):

        """
        Gửi mail cảnh báo các quyền (cổ phiếu) có trên VSD nhưng Flex 220001 chưa có
        """

        table = self.dataFeed.tableForJob1
        # nếu table rỗng -> không gửi mail
        if table.empty:
            return

        table.insert(
            loc = 0,
            column = 'STT',
            value = range(1, table.shape[0] + 1)
        )
        table = table.rename(
            mapper = {
                'VSD.ThoiGian': 'Thời điểm đăng tin',
                'VSD.NgayDangKyCuoiCung': 'Ngày ĐKCC',
                'VSD.MaChungKhoan': 'Mã',
                'VSD.TieuDe': 'Tiêu đề',
                'VSD.LoaiQuyen': 'Loại quyền',
            },
            axis = 1
        )
        formatters = {
            'Thời điểm đăng tin': lambda x: x.strftime(r'%d/%m/%Y %H:%M') if x == x else '',
            'Ngày ĐKCC':  lambda x: x.strftime(r'%d/%m/%Y') if x == x else '',
        }
        tableHTML = table.to_html(
            index = False,
            justify = 'center',
            border = 1,
            formatters = formatters,
        )
        bodyHTML = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:100%">
                        Các quyền sau đây đã công bố thông tin trên website VSD 
                        nhưng hệ thống Flex chưa có dữ liệu. 
                        Vui lòng kiểm tra lại.
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        {tableHTML}
                    </p>
                    <p style="font-family:Times New Roman; font-size:80%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
        """
        mail = self.__outlook.CreateItem(0)
        mail.To = self.mailRecipients
        mail.Subject = f"Danh sách các quyền (cổ phiếu) đã công bố trên website VSD nhưng Flex 220001 chưa có dữ liệu"
        mail.HTMLBody = bodyHTML
        mail.Send()


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob2(self):

        """
        Gửi mail cảnh báo toàn bộ quyền có trên Flex 220001 nhưng VSD chưa có
        """

        table = self.dataFeed.tableForJob2
        # nếu table rỗng -> không gửi mail
        if table.empty:
            return

        table.insert(
            loc = 0,
            column = 'STT',
            value = range(1, table.shape[0] + 1)
        )
        table = table.rename(
            mapper = {
                'F220001.NgayDangKyCuoiCung': 'Ngày ĐKCC',
                'F220001.MaChungKhoan': 'Mã',
                'F220001.LoaiQuyen': 'Loại quyền',
                'F220001.MaThucHienQuyen': 'Mã Thực Hiện Quyền',
            },
            axis = 1
        )
        tableHTML = table.to_html(
            index=False,
            justify = 'center',
            border = 1,
            formatters = {'Ngày ĐKCC':  lambda x: x.strftime(r' %d/%m/%Y') if x == x else ''},
        )
        bodyHTML = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:100%">
                        Các quyền sau đây đã có điện vào Flex nhưng website VSD chưa công bố thông tin.
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        {tableHTML}
                    </p>
                    <p style="font-family:Times New Roman; font-size:80%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
        """
        mail = self.__outlook.CreateItem(0)
        mail.To = self.mailRecipients
        mail.Subject = f"Danh sách các quyền có trên Flex 220001 nhưng website VSD chưa công bố thông tin"
        mail.HTMLBody = bodyHTML
        mail.Send()


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob3(self):

        """
        Gửi mail cảnh báo toàn bộ quyền có trên Flex 220001 nhưng VSD chưa có
        """
        table = self.dataFeed.tableForJob3
        # nếu table rỗng -> không gửi mail
        if table.empty:
            return

        table.insert(
            loc = 0,
            column = 'STT',
            value = range(1, table.shape[0] + 1)
        )
        table = table.rename(
            mapper = {
                'F220001.NgayDangKyCuoiCung': 'Ngày ĐKCC',
                'F220001.MaChungKhoan': 'Mã',
                'F220001.LoaiQuyen': 'Loại quyền',
                'F220001.MaThucHienQuyen': 'Mã Thực Hiện Quyền',
                'F220001.TyLeChiaCoTucBangTien': 'Tỷ lệ chia cổ tức bằng tiền (%)',
                'F220001.Trung3ThongTin': 'Trùng 3 thông tin',
                'F220001.Trung4ThongTin': 'Trùng 4 thông tin',
            },
            axis = 1
        )
        tableHTML = table.to_html(
            index=False,
            justify = 'center',
            border = 1,
            formatters = {'Ngày ĐKCC':  lambda x: x.strftime(r' %d/%m/%Y') if x == x else ''},
        )
        bodyHTML = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:100%">
                        Các quyền sau đây đang trùng thông tin trên màn hình Flex 220001. 
                        Vui lòng kiểm tra lại.
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        {tableHTML}
                    </p>
                    <p style="font-family:Times New Roman; font-size:80%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
        """
        mail = self.__outlook.CreateItem(0)
        mail.To = self.mailRecipients
        mail.Subject = f"Danh sách các quyền đang bị trùng thông tin trên Flex 220001"
        mail.HTMLBody = bodyHTML
        mail.Send()


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob4(self):

        """
        Thao tác sửa các quyền trên Flex 220001
        """
        # lấy table của job 4 từ datafeed
        table = self.dataFeed.tableForJob4
        for index in table.index:
            # thao tác lọc record ngoài màn hình chính để chọn đúng record cần sửa
            # clear toàn bộ điều kiện lọc hiện có
            self.mainScreen.clearAllCriteria()
            # lọc theo điều kiện Mã Thực Hiện Quyền (kết quả ra duy nhất 1 dòng)
            self.mainScreen.selectMaThucHienQuyen(table.loc[index,'F220001.MaThucHienQuyen'])
            # click "Sửa" trên dòng duy nhất
            # để sau đó hiện lên rightWindow (rightWindow.exists() == True)
            self.mainScreen.clickAction('edit')
            # thao tác chỉnh sửa thông tin trong cửa sổ rightWindow
            # gọi đúng class để tạo đúng rightObject
            rightObject = table.loc[index,'VSD.RightObject']
            if rightObject.tenQuyen == 'TraLoiTucBangChungQuyen' and rightObject.soTienChiTra < 0:
                continue # không nhập các chứng quyền có GiaThanhToan < GiaThucHien
            RightScreenClass = screen.__dict__[rightObject.tenQuyen]
            rightScreen = RightScreenClass(self.mainScreen.rightWindow,rightObject)
            rightScreen.edit()


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob5(self):

        """
        Thao tác tạo mới các quyền trên Flex 220001
        """
        # lấy table của job 5 từ datafeed
        table = self.dataFeed.tableForJob5
        for index in table.index:
            # lấy rightObject
            rightObject = table.loc[index,'VSD.RightObject']
            if rightObject.tenQuyen == 'TraLoiTucBangChungQuyen' and rightObject.soTienChiTra < 0:
                continue # không nhập các chứng quyền có GiaThanhToan < GiaThucHien
            # thao tác tạo quyền mới từ mainScreen của F220001
            # để sau đó hiện lên rightWindow (rightWindow.exists() == True)
            self.mainScreen.clickAction('create')
            # gọi đúng class để tạo đúng rightObject
            RightScreenClass = screen.__dict__[rightObject.tenQuyen]
            rightScreen = RightScreenClass(self.mainScreen.rightWindow, rightObject)
            rightScreen.create()


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob6(self):

        """
        Gửi mail log report vào cuối ngày
        """
        table = self.dataFeed.tableForJob6
        table.insert(
            loc = 0,
            column = 'STT',
            value = range(1, table.shape[0] + 1)
        )
        table = table.rename(
            mapper = {
                'VSD.ThoiGian': 'Thời điểm đăng tin',
                'VSD.MaChungKhoan': 'Mã',
                'VSD.NgayDangKyCuoiCung': 'Ngày ĐKCC',
                'VSD.TieuDe': 'Tiêu đề',
                'VSD.URL': 'URL',
                'F220001.MaThucHienQuyen': 'Mã Thực Hiện Quyền',
                'Action': 'Thao tác',
                'Log.RunTime': 'Thời điểm thao tác',
                'Log.Status': 'Trạng thái',
                'Log.Message': 'Kết quả',
            },
            axis = 1
        )
        formatters = {
            'Thời điểm đăng tin': lambda x: x.strftime(r'%d/%m/%Y %H:%M') if x == x else '',
            'Ngày ĐKCC':  lambda x: x.strftime(r'%d/%m/%Y') if x == x else '',
            'Thời điểm thao tác': lambda x: x.strftime(r'%d/%m/%Y %H:%M') if x == x else 'Chưa thao tác',
        }
        tableHTML = table.to_html(
            index = False,
            justify = 'center',
            border = 1,
            formatters = formatters,
        )
        bodyHTML = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:100%">
                        Kết quả cập nhật tự động thông tin quyền trên màn hình 220001. 
                        Vui lòng xử lý bằng tay các quyền bị lỗi (ERROR) và kiểm tra lại 
                        các trường thông tin hệ thống đưa cảnh báo (WARNING).
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        {tableHTML}
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        <b>* Ghi chú:</b>
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        <i>
                        -  Sửa: Phần mềm tự động SỬA thông tin sự kiện quyền 
                        trên Flex đối với các trường hợp đã có thông tin sự 
                        kiện quyền trên website VSD và Flex đã nhận được điện 
                        thông tin sự kiện quyền 
                        từ VSD.
                        </i>
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        <i>
                        - Thêm mới: Tại ngày đăng ký cuối cùng, phần mềm tự 
                        động THÊM MỚI sự kiện quyền trên Flex đối với các 
                        trường hợp đã có thông tin trên website VSD nhưng 
                        Flex CHƯA nhận được điện thông
                        tin sự kiện quyền từ VSD.
                        </i>
                    </p>
                    <p style="font-family:Times New Roman; font-size:80%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
        """
        mail = self.__outlook.CreateItem(0)
        mail.To = self.mailRecipients
        mail.Subject = f"Kết quả cập nhật tự động thông tin quyền trên màn hình Flex 220001"
        mail.HTMLBody = bodyHTML
        mail.Send()


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob7(self):

        """
        Gửi mail danh sách các quyền hệ thống không phân loại được vào cuối ngày
        """

        table = self.dataFeed.tableForJob7
        # nếu table rỗng -> không gửi mail
        if table.empty:
            return

        table.insert(
            loc = 0,
            column = 'STT',
            value = range(1, table.shape[0] + 1)
        )
        table = table.rename(
            mapper = {
                'VSD.ThoiGian': 'Thời điểm đăng tin',
                'VSD.NgayDangKyCuoiCung': 'Ngày ĐKCC',
                'VSD.MaChungKhoan': 'Mã',
                'VSD.TieuDe': 'Tiêu đề',
                'VSD.URL': 'URL',
            },
            axis = 1
        )
        formatters = {
            'Thời điểm đăng tin': lambda x: x.strftime(r'%d/%m/%Y %H:%M') if x == x else '',
            'Ngày ĐKCC':  lambda x: x.strftime(r' %d/%m/%Y') if x == x else '',
        }
        tableHTML = table.to_html(
            index = False,
            justify = 'center',
            border = 1,
            formatters = formatters,
        )
        bodyHTML = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:100%">
                        Các thông báo quyền sau đây trên website VSD mà hệ thống không phân loại được. 
                        Vui lòng kiểm tra và xử lý bằng tay trên màn hình Flex 220001 nếu cần.
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        {tableHTML}
                    </p>
                    <p style="font-family:Times New Roman; font-size:80%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
        """
        mail = self.__outlook.CreateItem(0)
        mail.To = self.mailRecipients
        mail.Subject = f"Danh sách các quyền trên VSD hệ thống không phân loại được"
        mail.HTMLBody = bodyHTML
        mail.Send()


    @utils.Decorator.logJobs(logger=utils.Logging.logger)
    def doJob8(self):

        """
        Gửi mail danh sách các quyền TraLoiTucBangChungQuyen có GiaThanhToan < GiaThucHien
        """

        table = self.dataFeed.tableForJob8
        # nếu table rỗng -> không gửi mail
        if table.empty:
            return
        
        table.insert(
            loc = 0,
            column = 'STT',
            value = range(1, table.shape[0] + 1)
        )
        table = table.rename(
            mapper = {
                'VSD.URL': 'Thông tin quyền trên VSD',
                'HOSE.URL': 'Thông tin chứng quyền trên HOSE',
            },
            axis = 1
        )
        tableHTML = table.to_html(
            index = False,
            justify = 'center',
            border = 1,
        )
        bodyHTML = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Times New Roman; font-size:100%">
                        Các quyền Trả Lợi Tức Bằng Chứng Quyền sau đây không được nhập vào Flex 220001 
                        do Chứng Quyền có Giá Thanh Toán nhỏ hơn Giá Thực Hiện.
                    </p>
                    <p style="font-family:Times New Roman; font-size:100%">
                        {tableHTML}
                    </p>
                    <p style="font-family:Times New Roman; font-size:80%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
        """
        mail = self.__outlook.CreateItem(0)
        mail.To = self.mailRecipients
        mail.Subject = f"Danh sách các quyền Trả Lợi Tức Bằng Chứng Quyền không được nhập vào Flex 220001 do Chứng Quyền có Giá Thanh Toán nhỏ hơn Giá Thực Hiện"
        mail.HTMLBody = bodyHTML
        mail.Send()


    def __repr__(self):
        return __class__.__qualname__

